### ISSUE TITLE
zscaler-terraformer import fails with "unsuccessful request with status code: 400"

### ISSUE THREAD

**Issue by dzhang-dv** [zscaler/zscaler-terraformer#159]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### zscaler-terraformer version

v0.3.4

### Expected outcome

When running zscaler-terraformer import --resources="zia", authentication is successful and the tool pulls down the zia configuration.

### Actual outcome

Authentication seemed to succeed, but pulling any resources leads to a 400 error. 

`DEBU[0002] got unknown attribute configuration: key nw_applications, value <nil>, value type <nil> 
DEBU[0002] got unknown attribute configuration: key rule_id, value <nil>, value type <nil> 
DEBU[0002] got unknown attribute configuration: key src_ips, value <nil>, value type <nil> 
DEBU[0002] unexpected attribute struct type <nil> for block app_service_groups 
DEBU[0002] unexpected attribute struct type <nil> for block app_services 
DEBU[0002] unexpected attribute struct type <nil> for block labels 
DEBU[0002] unexpected attribute struct type <nil> for block location_groups 
DEBU[0002] unexpected attribute struct type <nil> for block locations 
DEBU[0002] unexpected attribute struct type <nil> for block nw_application_groups 
DEBU[0002] unexpected attribute struct type <nil> for block nw_service_groups 
DEBU[0002] unexpected attribute struct type <nil> for block src_ip_groups 
DEBU[0002] nested mode "single" for timeouts not recognised 
DEBU[0002] unexpected attribute struct type <nil> for block users 
terraform import zia_firewall_filtering_rule.resource_zscaler_proxy_traffic_778942 778942
INFO[0003] [ERROR] error while running import:exit status 1

Error: un-successful request with status code: 400 `

### Steps to reproduce

1. Run `zscaler-terraformer import --resources="zia"` with the parameters ziaCloud, ziaUsername, ziaPassword, and ziaApiKey included.

**Comment by willguibr** [comment]
@dzhang-dv You may want to check the username you're using for the import and if the account has the correct permissions to perform API calls to specific resources.
I also recommend upgrading the tool to the latest v1.0.0 version released this week.
