### ISSUE TITLE
generate output for resource type zia_url_filtering_rules creates invalid stanzas for override_groups and override_users

### ISSUE THREAD

**Issue by cl-rob** [zscaler/zscaler-terraformer#186]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### zscaler-terraformer version

zscaler-terraformer v1.1.0

### Expected outcome

Output stanzas for these types should generate lists, but instead generate repeated override clauses (which is invalid), ie:

```
override_groups {
  id = [ 1000, 1005 ]
}
```

### Actual outcome

```
resource "zia_url_filtering_rules" "resource_zia_url_filtering_rules_1034340" {
  # output trimmed...
  override_groups {
    id = 100000
  }
  override_groups {
    id = 100001
  }
  override_users {
    id = 200002
  }
  override_users {
    id = 200000
  }
}
```

### Steps to reproduce

With the latest release build for any platform, `zscaler-terraformer generate --resources="zia_url_filtering_rules"` on any rule with more than one override user or override group set. User and group elements generate normally as a list, however override users and override groups display this behavior.

**Comment by willguibr** [comment]
@cl-rob The issue has been addressed on the latest version v1.1.1.
