### ISSUE TITLE
Failed to signin the user ZPA_CLIENT_ID

### ISSUE THREAD

**Issue by pmoosh** [zscaler/zscaler-terraformer#218]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### zscaler-terraformer version

v1.3.0

### Expected outcome

Should authenticate with given credentials
I am using the same credentials I use to run terraform plan successfully. For a terraform run the credentials are stored in `~/.zpa/credentials.json`
I tested both options inline and with with environment variables.
Q: Do I need Credentials with different permissions?

### Actual outcome

Failed to signin the user ZPA_CLIENT_ID=Mj............, got http status:401, response body:{
  "id" : "invalid_client",
  "reason" : "Client authentication failed."
} 

### Steps to reproduce

run:
zscaler-terraformer generate --resource-type "zpa_application_segment" --zpa_cloud="PRODUCTION" --zpa_customer_id="......

### References

None

**Comment by willguibr** [comment]
This authentication method is no longer supported. Please refer to the change log and README.

**Comment by pmoosh** [comment]
@willguibr - I was using environment variables and inline credentials as described in the README not the credentials file.

**Comment by willguibr** [comment]
@pmoosh

**Comment by willguibr** [comment]
@pmoosh Inline credentials work in the following way as described in the README section [here](https://github.com/zscaler/zscaler-terraformer#:~:text=ZPA%20Inline%20Authentication)
See example below
```sh
zscaler-terraformer generate --resources="zpa_application_segment" \
--zpa_client_id="*************" \
--zpa_client_secret="*************"" \
--zpa_customer_id="="*************"" \
--zpa_cloud="BETA"
```
Note: the generate command simply generate and display the HCL configuration in the screen but do not generate the .tf files.

The error you've posted indicates 401, "id" : "invalid_client",, which means something is not correct with your credentials. In most cases it's related to the client secret non escaped special characters.

In all our tests both methods, inline and environment variables are working as expected. I'd recommend checking your credentials outside of the tool or ensure special characters are properly escaped. The special characters escape is a Linux / Unix CLI issue.
If you require further assistance, we recommend to open a ticket with our support team for further investigation.

Zscaler DevRel.

**Comment by pmoosh** [comment]
@willguibr - It works with env vars, I am using zsh. What I had to do was using single quotes instead of double.
