### ISSUE TITLE
Error "Custom File Hash feature is not enabled for your org"

### ISSUE THREAD

**Issue by snowman386** [zscaler/zscaler-terraformer#224]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### zscaler-terraformer version

zscaler-terraformer v1.3.2 Terraform version: Terraform v1.9.5 on (windows_amd64)

### Expected outcome

The tool to run without errors

### Actual outcome

I am getting this error when running the tool
`time="2024-08-29T16:22:37-04:00" level=fatal msg="FAILED: GET, https://zsapi.zscalerthree.net/api/v1/behavioralAnalysisAdvancedSettings, 400, 400 , {\"code\":\"INVALID_INPUT_ARGUMENT\",\"message\":\"Custom File Hash feature is not enabled for your org\"}, api responded with code: 400"`

Not sure if this error is stopping the tool from completing but that is the last line output to the console. Tried running with `--exclude='zia_sandbox_behavioral_analysis'` but still get this error output. This feature is indeed not available in our console. Just want to make sure the tool is completing successfully despite the error.

### Steps to reproduce

run `zscaler-terraformer import --resources="zia" --exclude='zia_sandbox_behavioral_analysis'` or `zscaler-terraformer import --resources="zia"`

**Comment by willguibr** [comment]
@snowman386 This is a license issue. Please contact Zscaler support and ask to enable the "Custom File Hash" feature.

Regards

Zscaler DevRel

**Comment by snowman386** [comment]
> @snowman386 This is a license issue. Please contact Zscaler support and ask to enable the "Custom File Hash" feature.
> 
> Regards
> 
> Zscaler DevRel

@willguibr How do you figure that? I ran with the --exclude='zia_sandbox_behavioral_analysis' option so the tool should not be crashing whether any sandbox features are activated or not. Also this error was when running against a Zscaler Demo Center tenant. Your guy's tools should run against your demo environments without errors.

**Comment by willguibr** [comment]
@snowman386 
We have released a minor release version to handle license issues more gracefully going forward.
The tool wasn't "crashing" as stated in your previous answer. It was simply displaying the error returned from the API as an unlicensed feature.
Our tools are executed against all Zscaler clouds, which are fully licensed; hence, the potential miss on handling the error in question.
Either way, the fix has been deployed and is available via version v1.3.3.

Regards

Zscaler DevRel.

**Comment by snowman386** [comment]
Thank you. This will definitely help me sell the terraformer solution to customers without having to run it against real customer environments.
