### ISSUE TITLE
Brew install failing due to sha256 mismatch

### ISSUE THREAD

**Issue by bhavya-eg** [zscaler/zscaler-terraformer#234]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### zscaler-terraformer version

1.3.4

### Expected outcome

Expected zscaler-terraformer to be installed properly

### Actual outcome

brew install --cask zscaler/tap/zscaler-terraformer
==> Downloading https://github.com/zscaler/zscaler-terraformer/releases/download/v1.3.4/zscaler-terraformer_1.3.4_darwin_arm64.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/523216490/7a7a8dff-a842-488c-a668-a52d2bfdfca7?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduct
############################################################################################################################################################################################################### 100.0%
Error: SHA256 mismatch
Expected: 2f11be860c69bf1648f9acf377aa076c702ff9a764aae975df6c61eb3ef0238d
  Actual: d5e00bd420f355b6da108748623a0f7a43f0f4b4782bd5d0dfb3bb7a8d44dba3
    File: /Users/bdhuria/Library/Caches/Homebrew/downloads/fe603c1e338237793808675cd71892464ec734fe8ea46d850f2fb346f39dea7d--zscaler-terraformer_1.3.4_darwin_arm64.zip
To retry an incomplete download, remove the file above.

### Steps to reproduce

Just try and install the package
My system :
Chip: Apple M3 pro
OS: Sonoma 14.7

**Comment by bhavya-eg** [comment]
This issue got resolved by updating my brew version (Homebrew 4.4.6-13-gfa8af7c)
zscaler terraformer version installed is 1.3.4 and terraform version is 1.9.8
I didn't do anything else differently, just that brew got updated which fixed this issue

**Comment by chunj9** [comment]
this same issue appears to be reintroduced in homebrew 4.4.12
