### ISSUE TITLE
add license / feature exception handling to zpa isolation

### ISSUE THREAD

**Issue by snowman386** [zscaler/zscaler-terraformer#242]
### Current `zscaler-terraformer` version

zscaler-terraformer v1.3.5 Terraform version: Terraform v1.10.3 on (windows_amd64)

### Description

the ZPA import fails without excluding:

- zpa_cloud_browser_isolation_banner
- zpa_cloud_browser_isolation_certificate
- zpa_cloud_browser_isolation_external_profile

with error:
`time="2024-12-26T13:07:10-05:00" level=fatal msg="FAILED: GET, https://config.zpagov.net/cbiconfig/cbi/api/customers/XXXXXXXXXX/certificates, 404, 404 Not Found, {\"reason\":\"No handler found\",\"id\":\"resource.not.found\"}"`

### Use cases

It would be ideal if the ZPA import imported everything that was available in a tenant without having to exclude everything that is not licensed. This would greatly improve the import time if this iterative exclusion process is eliminated.

### Potential `zscaler-terraformer` usage

run zscaler-terraformer import --resources="zpa" and have all supported features imported without error.

**Comment by willguibr** [comment]
We are not implementing this.
This is a Cloud browser isolation api limitation which does not provide us information on license status.
Please use the --exclude flag as per the readme.

Zscaler DevRel.
