### ISSUE TITLE
zia_firewall_filtering_rule.tf: Inappropriate value for attribute "id": list of number required.

### ISSUE THREAD

**Issue by yonz2** [zscaler/zscaler-terraformer#53]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### zscaler-terraformer version

zscaler-terraformer v0.1.0

### Expected outcome

When running `terraform plan` on the output from zscaler-terraformer, the plan should complete.

### Actual outcome

When running `terraform plan` on the output from zscaler-terraformer an error is reported:

```
 Error: Incorrect attribute value type

   on zia_firewall_filtering_rule.tf line 43, in resource "zia_firewall_filtering_rule" "resource_firewall_2_93056":
   43:     id = 126582
 
 Inappropriate value for attribute "id": list of number required.
```

### Steps to reproduce

1) Run` ./zscaler-terraformer import --resources="zia_url_categories"` (e.g- using a  betacloud account credentials)
2) CD into the `zia `directory and run `terraform init`
3) Follwoed by `terraform plan`

**Comment by willguibr** [comment]
Hi @yonz2 I am not seeing the same issue you've reported when running both terraform plan and/or terraform apply after the import for zia_url_categories.
<img width="1265" alt="Screen Shot 2023-01-22 at 3 14 56 PM" src="https://user-images.githubusercontent.com/23208337/213945617-5ca2b06d-eb90-487c-8a47-522121ef4ab0.png">
Can you provide some further details or set the following env variables, then provide the log file?

```bash
export TF_LOG="TRACE"
export TF_LOG_PATH="terraform.log"
export ZSCALER_SDK_LOG=true
export ZSCALER_SDK_VERBOSE=true
```
Thank you

**Comment by willguibr** [comment]
No response in this case for over 1 year. Closing it.
