### ISSUE TITLE
Lat/Long rounded to an integer value

### ISSUE THREAD

**Issue by yonz2** [zscaler/zscaler-terraformer#54]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### zscaler-terraformer version

zscaler-terraformer v0.1.0

### Expected outcome

Lat/Long value kept as decimal values (four decimal places) NOT integers

### Actual outcome

In the generated `zia_traffic_forwarding_static_ip.tf` the lat/long values are rounded to an integer value, should be kept as is (decimal)

```
resource "zia_traffic_forwarding_static_ip" "resource_14259" {
  geo_override = false
  ip_address   = "127.0.0.0"
  latitude     = 51
  longitude    = 9
}

```

in the` terraform.tfstate` file the value is correct:

```
      "mode": "managed",
      "type": "zia_traffic_forwarding_static_ip",
      "name": "resource_14259",
      "provider": "provider[\"registry.terraform.io/zscaler/zia\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "comment": "",
            "geo_override": false,
            "id": "14259",
            "ip_address": "87.139.250.138",
            "last_modified_by": [],
            "latitude": 51.3321,
            "longitude": 9.4939,
            "managed_by": [],
            "routable_ip": true,
            "static_ip_id": 14259
          },
          "sensitive_attributes": [],
          "private": "eyJzY2hlbWFfdmVyc2lvbiI6IjAifQ=="
        }
      ]
    },
```
this results in a change when running terraform. See output from `terraform plan` : 

```
  # zia_traffic_forwarding_static_ip.resource_14259 will be updated in-place
  ~ resource "zia_traffic_forwarding_static_ip" "resource_14259" {
        id           = "14259"
      ~ latitude     = 51.3321 -> 51
      ~ longitude    = 9.4939 -> 9
        # (4 unchanged attributes hidden)

```
lat/long should not be changed.

### Steps to reproduce

Run `terraform plan` on the output from `zscaler-terraformer`

**Comment by willguibr** [comment]
Hi @yonz2, the issue has been addressed in the latest release v0.2.0
Thank you
