### ISSUE TITLE
ZPA Resource Name Transforms

### ISSUE THREAD

**Issue by drank-sinatra** [zscaler/zscaler-terraformer#56]
### Current `zscaler-terraformer` version

latest

### Description

When doing a `zscaler-terraform import`, a resource name like `resource "zpa_policy_access_rule" "resource_audit_allow_72057766911039919"` is automatically generated. What would be great is if the transformation from this name to the actual resource name specified in the resource (`  name                = "Audit_Allow"` for the above example) could be done automatically by reading that line in the resource definition and re-writing the generated name after import. Currently I have to do this manually.

### Use cases

This bit of automation would drastically speed process of migrating to IaC.

### Potential `zscaler-terraformer` usage

This should happen automatically during `zscaler-terraformer import` much like it does in the original Terraformer application when importing cloud resources in bulk.

**Comment by willguibr** [comment]
Hi @drank-sinatra The issue has been addressed in the latest release v0.2.0
Thank you

**Comment by drank-sinatra** [comment]
Thank you so much! I will update and try pulling in ZIA tomorrow.
