### ISSUE TITLE
Automatic Provider File Does not Pull Credentials from .zscaler-terraformer.yaml

### ISSUE THREAD

**Issue by drank-sinatra** [zscaler/zscaler-terraformer#57]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### zscaler-terraformer version

0.1.0

### Expected outcome

When running `zscaler-terraformer import`, a Provider file named `zpa-provider.tf` or `zia-provider.tf` is automatically created. I expect it to create the file with both the provider and the credential information populated in my `.zscaler-terraformer.yaml` file
```
terraform {
    required_providers {
    zpa = {
      source  = "zscaler/zpa"
    }
  }
}

provider "zpa" {
  # Sensitive items removed
  zpa_client_id         = ""
  zpa_client_secret     = ""
  zpa_customer_id       = ""
  zpa_cloud             = "GOV"
}
```

### Actual outcome

The automatically created provider file only has the provider defined like this:
```
terraform {
    required_providers {
    zpa = {
      source  = "zscaler/zpa"
    }
  }
}
```

I have populated .zscaler-terraformer.yaml in the default location with all of the necessary information for each service in what I believe to be the proper syntax, but it does not get pulled over when I run an import, requiring me to overwrite the file with the one I created manually and run the import again.

```yaml
# Sensitive items removed
zpaClientID: ""
zpaClientSecret: ""
zpaCustomerID: ""
zpaCloud: "GOV"
ziaUsername: ""
ziaPassword: ""
ziaApiKey: ""
ziaCloud: "zscalergov"
```

### Steps to reproduce

1. Create a `.zscaler-terraformer.yaml` file in the default location
2. Run `zscaler-terraformer import` on some or all resources
3. The command will complete but errors will be displayed in the terminal
4. Overwrite the automatically created Provider file with one created manually that has credentials defined
5. Run `zscaler-terraformer import` on some or all resources
6. The command will complete without error and resources will be imported

**Comment by willguibr** [comment]
Hi @drank-sinatra 
Thanks for creating this issue. 
I can confirm there's an issue with the way credentials are being read from the configuration file.
In the meantime, I encourage you to use environment variables instead in the following format which is more recommended and is the current working method.

```bash
# ZPA Configuration
export ZPA_CLIENT_ID=""
export ZPA_CLIENT_SECRET=""
export ZPA_CUSTOMER_ID=""
export ZPA_CLOUD="" --> Optional argument ["PRODUCTION", "BETA", "GOV", "PREVIEW"]
```

```bash
# ZIA Configuration
export ZIA_USERNAME=''
export ZIA_PASSWORD=''
export ZIA_API_KEY=''
export ZIA_CLOUD=--> Optional argument ["zscaler", "zscalerone", "zscalertwo", "zscalerthree", "zscloud", "zscalerbeta", "zscalergov"]
```
Thank you

Feel free to reach out via email as well wguilherme@you_know_the_rest.com ;)

**Comment by drank-sinatra** [comment]
Ah, good to know! Thanks so much. :)

**Comment by drank-sinatra** [comment]
I actually just remembered that I had tried this before, and it fails to add my secret because there is a `'` in it which ZSH interprets as a literal quote and thus breaks. I suppose I could get a new key though.

<img width="938" alt="image" src="https://user-images.githubusercontent.com/70671790/213806642-718a05f8-91f8-435b-8268-591417704ade.png">

**Comment by willguibr** [comment]
Hi @drank-sinatra 
Would you mind reaching out offline? Also, I recommend that you delete the previous screenshot, as this information should be treated as private.
Feel free to reach out via email wguilherme@you_know_the_rest.com ;)
