### ISSUE TITLE
Crash when a resource is not licensed

### ISSUE THREAD

**Issue by yonz2** [zscaler/zscaler-terraformer#69]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### zscaler-terraformer version

zscaler-terraformer v0.2.1

### Expected outcome

Ignore the particular resource, if it is not licensed

### Actual outcome

Fatal error:

`FATA[0053] FAILED: GET, https://zsapi.zscalerbeta.net/api/v1/dlpDictionaries?&pageSize=1000&page=1, 403, 403 , {"code":"NOT_SUBSCRIBED","message":"Data Leak Protection (DLP) subscription is required, but it is currently not started."}, api responded with code: 403 `

### Steps to reproduce

run `./zscaler-terraformer import --resources="zia" --verbose`  with a user not licensed for e.g. "DLP"

**Comment by willguibr** [comment]
The tool already ignores resources which return an empty response during the API call; however, it still queries that resource to find out if there is anything to be imported.
Question:
1. Can you confirm if the DLP module is properly licensed in your Beta tenant?
2. Can you try importing by using the following command: ./zscaler-terraformer import --resources="zia_dlp_dictionaries" --verbose
Thanks

**Comment by yonz2** [comment]
Running:
```
../zscaler-terraformer import --resources="zia_dlp_dictionaries" \
            --ziaCloud 'zscalerbeta' \
            --ziaUsername '<<UserName>>' \
            --ziaPassword '<<Password>>' \
            --ziaApiKey '<<API-Key>>' \
            --verbose
```
Returns:
```
DEBU[0000] initializing zscaler-sdk-go[ZIA]              ziaCloud=ziaCloud ziaUsername=<<UserName>>
FATA[0002] FAILED: GET, https://zsapi.zscalerbeta.net/api/v1/dlpDictionaries?&pageSize=1000&page=1, 403, 403 , {"code":"NOT_SUBSCRIBED","message":"Data Leak Protection (DLP) subscription is required, but it is currently not started."}, api responded with code: 403 
```
and the DLP License seems NOT to be there:
![2023-02-20 09_29_49-Window](https://user-images.githubusercontent.com/13886257/220053765-b6c79399-b4d4-41e0-a58e-af52c3e9612d.png)

**Comment by willguibr** [comment]
Ok, so you don't have a DLP license in place; hence the reason you're receiving this message back from the API.
In future versions, I'll make sure to abstract this message. Also, the tool won't import predefined, prebuilt resources, so even in a properly licensed tenant, the HCL would not be generated.
In other words, the only issue is that the tool is not abstracting the upstream API message.
